### ISSUE TITLE
Order of fields in exported file

### ISSUE THREAD

**Issue by aConar** [otto-torino/django-admin-export-action#2]
* Django Admin Export Action version: 0.24
* Django version: 3.2.8
* Python version: 3.8.12
* Operating System: Ubuntu Focal

First thanks for this great django action.
I have an issue with exported files, more precisely, the order of the fields is different as in admin forms. It would be great if the order of fields in exported files be the same as in admin forms (or as in model field definition or maybe custom user defined?).
Thanks in advance
Alej

**Comment by abidibo** [comment]
Not so easy to add, currently model fields are introspected using
```
model._meta.get_fields()
```
Maybe in the feature we'll add a sort functionality when selecting the fields to be exported. Not so easy though because of all nested relationships
